FROM python:3.8-slim

WORKDIR /app/
COPY requirements_forecast.txt /app/
RUN pip install -r ./requirements_forecast.txt
ADD ./forecast /app/
ADD ./shared_volume /app/

EXPOSE 8081

ENTRYPOINT python /app/form_submit.py